time python Torch_CBNE/scripts/calibrate_cbne.py \
  --path ../quantinuum/CBNE/graphs/Graph-1.graphml \
  --target 0.444 \
  --epsilon 0.1 \
  --deg-limit -1 3 \
  --iter-start 3000 \
  --iter-max 20000 \
  --iter-factor 1.5 \
  --seeds 123 \
  --tolerance 5e-4 \
  --min-improvement 2.5e-4 \
  --device cpu \
  --summary-json logs/calibration/graph1_summary.json
